"""Actualizacion1.0

Revision ID: 04a5d926f471
Revises: 5d80081dc388
Create Date: 2018-04-05 01:17:24.986679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a5d926f471'
down_revision = '5d80081dc388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biceps', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_biceps_nombreEjer'), 'biceps', ['nombreEjer'], unique=False)
    op.add_column('cuadriceps', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_cuadriceps_nombreEjer'), 'cuadriceps', ['nombreEjer'], unique=False)
    op.add_column('femoral', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_femoral_nombreEjer'), 'femoral', ['nombreEjer'], unique=False)
    op.add_column('hombro', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_hombro_nombreEjer'), 'hombro', ['nombreEjer'], unique=False)
    op.add_column('pantorrilla', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_pantorrilla_nombreEjer'), 'pantorrilla', ['nombreEjer'], unique=False)
    op.add_column('pecho', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_pecho_nombreEjer'), 'pecho', ['nombreEjer'], unique=False)
    op.add_column('triceps', sa.Column('nombreEjer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_triceps_nombreEjer'), 'triceps', ['nombreEjer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triceps_nombreEjer'), table_name='triceps')
    op.drop_column('triceps', 'nombreEjer')
    op.drop_index(op.f('ix_pecho_nombreEjer'), table_name='pecho')
    op.drop_column('pecho', 'nombreEjer')
    op.drop_index(op.f('ix_pantorrilla_nombreEjer'), table_name='pantorrilla')
    op.drop_column('pantorrilla', 'nombreEjer')
    op.drop_index(op.f('ix_hombro_nombreEjer'), table_name='hombro')
    op.drop_column('hombro', 'nombreEjer')
    op.drop_index(op.f('ix_femoral_nombreEjer'), table_name='femoral')
    op.drop_column('femoral', 'nombreEjer')
    op.drop_index(op.f('ix_cuadriceps_nombreEjer'), table_name='cuadriceps')
    op.drop_column('cuadriceps', 'nombreEjer')
    op.drop_index(op.f('ix_biceps_nombreEjer'), table_name='biceps')
    op.drop_column('biceps', 'nombreEjer')
    # ### end Alembic commands ###
