"""'Actualizacion_tablas_de_rutina'

Revision ID: 7a38ed63f63c
Revises: 7ea06129dadf
Create Date: 2018-03-30 23:04:55.252155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a38ed63f63c'
down_revision = '7ea06129dadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biceps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biceps_descanso'), 'biceps', ['descanso'], unique=True)
    op.create_index(op.f('ix_biceps_peso'), 'biceps', ['peso'], unique=True)
    op.create_index(op.f('ix_biceps_repeticiones'), 'biceps', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_biceps_semana'), 'biceps', ['semana'], unique=True)
    op.create_index(op.f('ix_biceps_series'), 'biceps', ['series'], unique=True)
    op.create_table('cuadriceps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuadriceps_descanso'), 'cuadriceps', ['descanso'], unique=True)
    op.create_index(op.f('ix_cuadriceps_peso'), 'cuadriceps', ['peso'], unique=True)
    op.create_index(op.f('ix_cuadriceps_repeticiones'), 'cuadriceps', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_cuadriceps_semana'), 'cuadriceps', ['semana'], unique=True)
    op.create_index(op.f('ix_cuadriceps_series'), 'cuadriceps', ['series'], unique=True)
    op.create_table('femoral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_femoral_descanso'), 'femoral', ['descanso'], unique=True)
    op.create_index(op.f('ix_femoral_peso'), 'femoral', ['peso'], unique=True)
    op.create_index(op.f('ix_femoral_repeticiones'), 'femoral', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_femoral_semana'), 'femoral', ['semana'], unique=True)
    op.create_index(op.f('ix_femoral_series'), 'femoral', ['series'], unique=True)
    op.create_table('hombro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hombro_descanso'), 'hombro', ['descanso'], unique=True)
    op.create_index(op.f('ix_hombro_peso'), 'hombro', ['peso'], unique=True)
    op.create_index(op.f('ix_hombro_repeticiones'), 'hombro', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_hombro_semana'), 'hombro', ['semana'], unique=True)
    op.create_index(op.f('ix_hombro_series'), 'hombro', ['series'], unique=True)
    op.create_table('pantorrilla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pantorrilla_descanso'), 'pantorrilla', ['descanso'], unique=True)
    op.create_index(op.f('ix_pantorrilla_peso'), 'pantorrilla', ['peso'], unique=True)
    op.create_index(op.f('ix_pantorrilla_repeticiones'), 'pantorrilla', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_pantorrilla_semana'), 'pantorrilla', ['semana'], unique=True)
    op.create_index(op.f('ix_pantorrilla_series'), 'pantorrilla', ['series'], unique=True)
    op.create_table('pecho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pecho_descanso'), 'pecho', ['descanso'], unique=True)
    op.create_index(op.f('ix_pecho_peso'), 'pecho', ['peso'], unique=True)
    op.create_index(op.f('ix_pecho_repeticiones'), 'pecho', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_pecho_semana'), 'pecho', ['semana'], unique=True)
    op.create_index(op.f('ix_pecho_series'), 'pecho', ['series'], unique=True)
    op.create_table('triceps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('series', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('descanso', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triceps_descanso'), 'triceps', ['descanso'], unique=True)
    op.create_index(op.f('ix_triceps_peso'), 'triceps', ['peso'], unique=True)
    op.create_index(op.f('ix_triceps_repeticiones'), 'triceps', ['repeticiones'], unique=True)
    op.create_index(op.f('ix_triceps_semana'), 'triceps', ['semana'], unique=True)
    op.create_index(op.f('ix_triceps_series'), 'triceps', ['series'], unique=True)
    op.add_column('user', sa.Column('Altura', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('Peso', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_Altura'), 'user', ['Altura'], unique=True)
    op.create_index(op.f('ix_user_Peso'), 'user', ['Peso'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_Peso'), table_name='user')
    op.drop_index(op.f('ix_user_Altura'), table_name='user')
    op.drop_column('user', 'Peso')
    op.drop_column('user', 'Altura')
    op.drop_index(op.f('ix_triceps_series'), table_name='triceps')
    op.drop_index(op.f('ix_triceps_semana'), table_name='triceps')
    op.drop_index(op.f('ix_triceps_repeticiones'), table_name='triceps')
    op.drop_index(op.f('ix_triceps_peso'), table_name='triceps')
    op.drop_index(op.f('ix_triceps_descanso'), table_name='triceps')
    op.drop_table('triceps')
    op.drop_index(op.f('ix_pecho_series'), table_name='pecho')
    op.drop_index(op.f('ix_pecho_semana'), table_name='pecho')
    op.drop_index(op.f('ix_pecho_repeticiones'), table_name='pecho')
    op.drop_index(op.f('ix_pecho_peso'), table_name='pecho')
    op.drop_index(op.f('ix_pecho_descanso'), table_name='pecho')
    op.drop_table('pecho')
    op.drop_index(op.f('ix_pantorrilla_series'), table_name='pantorrilla')
    op.drop_index(op.f('ix_pantorrilla_semana'), table_name='pantorrilla')
    op.drop_index(op.f('ix_pantorrilla_repeticiones'), table_name='pantorrilla')
    op.drop_index(op.f('ix_pantorrilla_peso'), table_name='pantorrilla')
    op.drop_index(op.f('ix_pantorrilla_descanso'), table_name='pantorrilla')
    op.drop_table('pantorrilla')
    op.drop_index(op.f('ix_hombro_series'), table_name='hombro')
    op.drop_index(op.f('ix_hombro_semana'), table_name='hombro')
    op.drop_index(op.f('ix_hombro_repeticiones'), table_name='hombro')
    op.drop_index(op.f('ix_hombro_peso'), table_name='hombro')
    op.drop_index(op.f('ix_hombro_descanso'), table_name='hombro')
    op.drop_table('hombro')
    op.drop_index(op.f('ix_femoral_series'), table_name='femoral')
    op.drop_index(op.f('ix_femoral_semana'), table_name='femoral')
    op.drop_index(op.f('ix_femoral_repeticiones'), table_name='femoral')
    op.drop_index(op.f('ix_femoral_peso'), table_name='femoral')
    op.drop_index(op.f('ix_femoral_descanso'), table_name='femoral')
    op.drop_table('femoral')
    op.drop_index(op.f('ix_cuadriceps_series'), table_name='cuadriceps')
    op.drop_index(op.f('ix_cuadriceps_semana'), table_name='cuadriceps')
    op.drop_index(op.f('ix_cuadriceps_repeticiones'), table_name='cuadriceps')
    op.drop_index(op.f('ix_cuadriceps_peso'), table_name='cuadriceps')
    op.drop_index(op.f('ix_cuadriceps_descanso'), table_name='cuadriceps')
    op.drop_table('cuadriceps')
    op.drop_index(op.f('ix_biceps_series'), table_name='biceps')
    op.drop_index(op.f('ix_biceps_semana'), table_name='biceps')
    op.drop_index(op.f('ix_biceps_repeticiones'), table_name='biceps')
    op.drop_index(op.f('ix_biceps_peso'), table_name='biceps')
    op.drop_index(op.f('ix_biceps_descanso'), table_name='biceps')
    op.drop_table('biceps')
    # ### end Alembic commands ###
