"""Tabla de usuarios actualizada

Revision ID: 7ea06129dadf
Revises: bf7fe1550d23
Create Date: 2018-03-28 19:46:42.301945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea06129dadf'
down_revision = 'bf7fe1550d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('edad', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('usersurname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_edad'), 'user', ['edad'], unique=True)
    op.create_index(op.f('ix_user_usersurname'), 'user', ['usersurname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usersurname'), table_name='user')
    op.drop_index(op.f('ix_user_edad'), table_name='user')
    op.drop_column('user', 'usersurname')
    op.drop_column('user', 'edad')
    # ### end Alembic commands ###
