"""'Valores_agregados_User'

Revision ID: 8865af400ada
Revises: 7a38ed63f63c
Create Date: 2018-04-01 00:57:54.820379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8865af400ada'
down_revision = '7a38ed63f63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('userid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=True)
    op.create_index(op.f('ix_user_userid'), 'user', ['userid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_userid'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_column('user', 'userid')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
